### ISSUE TITLE
base de données intégrée au plugin

### ISSUE THREAD

**Issue by Skolman360** [fhebuterne/MarketPlace#10]
### Feature related to a problem ?

l'inconvénient que j'ai eu c'est que dans certains cas il y a pas mal de latence avec les base de données mysql par cause d'être host sur un serveur différent (pour des raisons variables) ce qui cause un soucis démontré dans cette vidéo https://user-images.githubusercontent.com/51415372/167258158-8794d53b-4e85-4de9-8fea-1af7bdc79723.mp4

### Describe the solution you'd like

ce que je propose c'est de mettre en place une base de donnée intégrée au plugin comme par exemple avec SQLite ce qui est la solution de certains autres plugins. si une solution similaire existe déja dans le plugin je serais ravis de savoir comment l'utiliser.

**Comment by fhebuterne** [comment]
Available in MarketPlace 1.6.0 by using SQLITE in database type in config.yml
