### ISSUE TITLE
How to disable expiration?

### ISSUE THREAD

**Issue by BurpOfFury** [fhebuterne/MarketPlace#34]
### Question

Hello, I am using this plugin on my server and would like to know if there's a way to disable the listing expiration in the config so items that are put up for sale stay there indefinitely until someone purchases them.

**Comment by fhebuterne** [comment]
Hi, this is available since 1.11.0 version : https://www.spigotmc.org/resources/marketplace-1-12-1-20-4.92212/updates

**Comment by mhtvsSFrpHdE** [comment]
But what exactly is the config?

```
  "expiration": {
    "playerToListings": 604800,
    "listingsToMails": 604800,
    "listingsToMailsNotifCommand": [
      "mail send {{playerPseudo}} your item {{quantity}}x{{itemStack}} has expired from listings and its in your mailbox."
    ],
    "mailsToDeleteNotifCommand": [
      "mail send {{playerPseudo}} your item {{quantity}}x{{itemStack}} has expired from mailbox and has been deleted."
    ]
  },
```

There isn't a config like "enable: true|false".

**Comment by mhtvsSFrpHdE** [comment]
By check the source code and discovered `allExpirationsDisabled`, to set this config true, add these to config
```
...
    "expiration": {
        "listingsToMailsEnabled": false,
        "mailsToDeleteEnabled": false,
...
```

And I think expiration should be `false` by default because it risks people to lose their items, until they forgot there is an expiration system.

```
https://github.com/fhebuterne/MarketPlace/blob/6243cf0187806054b1932ba541b7e705cd78b104/common/src/main/kotlin/fr/fabienhebuterne/marketplace/domain/config/Config.kt#L48
https://github.com/fhebuterne/MarketPlace/blob/6243cf0187806054b1932ba541b7e705cd78b104/common/src/main/kotlin/fr/fabienhebuterne/marketplace/services/ExpirationService.kt#L23
```
